# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGpZHoW8oOmFsBVFai0rGVX6JhsSApNh
"""

import pandas as pd
import numpy as np
import matplotlib as mlp
from google.colab import files 
uploaded =files.upload()

datafiles=pd.read_csv("Salary_Data.csv")

datafiles

s.describe

datafiles.describe()

x=datafiles.iloc[:,:-1].values
y=datafiles.iloc[:,1].values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)
y_pred

mlp.scatter(x_train,y_train,color='red')
mlp.plot(x_train,regressor.predict(x_train),color='blue')
mlp.title("salary vs experience(training set"))

import matplotlib.pyplot as mlp

mlp.scatter(x_train,y_train,color='red')
mlp.plot(x_train,regressor.predict(x_train),color='blue')

